### ISSUE TITLE
ARSIS Project README

### ISSUE THREAD

**Issue by isaacdenny** [BSU-SUITS-Team/ARSIS-6#15]
**Is your feature request related to a problem? Please describe.**
An informative project description / highlights for outside viewers of the project, new members, or members who have not used version control before. Also should define how to get started developing (fork, dependencies).

**Describe the solution you'd like**
New members should be able to get started messing around in their own forks and getting used to Docker, Unity, and other such tools.

**Describe alternatives you've considered**
Put it on Discord, or we could just tell new members how to start project... but that could get repetitive.

**Additional context**
This would help keep the team leads from having to answer as many questions.

**Comment by cburnell** [comment]
This is a really good idea. I think the readme might be limited in scope to just how to get stuff running? 
I create a few wiki pages for resources but it is certainly not an exhaustive list. Do you want to take a stab at creating the README?

**Comment by isaacdenny** [comment]
Can do! I think I might wait until we have a bit in the repo to run than just the Unity project (maybe when the telemetry PR gets merged). I'll get something simple up for now.
