### ISSUE TITLE
Add Biometrics Endpoint

### ISSUE THREAD

**Issue by dignojrteogalbo** [BSU-SUITS-Team/ARSIS-6#21]
**Is your feature request related to a problem? Please describe.**
Need an endpoint to provide mock data to telemetry.

**Describe the solution you'd like**
Endpoint with "/biometrics/{user}" which displays the data in the format:
{ "bpm": number, "o2": number, "battery": number }

**Describe alternatives you've considered**

**Additional context**

**Comment by isaacdenny** [comment]
I'll have this done by end of today
