### ISSUE TITLE
Add Users Endpoint

### ISSUE THREAD

**Issue by dignojrteogalbo** [BSU-SUITS-Team/ARSIS-6#25]
**Is your feature request related to a problem? Please describe.**
Need an endpoint to provide mock data to telemetry.

**Describe the solution you'd like**
Endpoint with "/users" which has the slugs "/join", "/leave", and "/list" which return data in the format:
(join) -> {"id": number, "timeCreated": number }
(leave) -> {"id": number, "timeCreated": number }
(list) -> {"users": [ {"id": number, "timeCreated": number }... ] }

**Describe alternatives you've considered**

**Additional context**

**Comment by isaacdenny** [comment]
oh my b closed this too early
