### ISSUE TITLE
Remove the vscode and modify git ignore

### ISSUE THREAD

**Issue by cburnout** [BSU-SUITS-Team/ARSIS-6#7]
**Describe the bug**
A vscode directory is in the repo which isn't necessarily what everyones preferences are so we should remove it and add it to the git ignore (good first issue)

**To Reproduce**
1. look at files and see .vscode/ exists

**Expected behavior**
It should be deleted

**Screenshots**
NA

**Desktop (please complete the following information):**
 NA

**Smartphone (please complete the following information):**
NA 
**Additional context**
NA

**Comment by cburnell** [comment]
I don't think so I was thinking this would be a good practice one where we can do the Fork -> Branch -> Pull Request(PR) -> Code Review (CR) -> Merge
